# Travis CI configuration file to build a Jekyll project 
# and deploy the static files to GitHub Pages afterwards
# Maintained by Lutz Thies (https://github.com/7HAL32)
# July 2017

language: ruby
rvm:
  - 2.2

sudo: false 
# prevent Travis from starting clean everytime to speed up builds
cache:
  bundler: true
  yarn: true
  directories:
  - node_modules

before_install:
  # use nvm to install npm, as it is only included by Travis CI in node_js projects
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  # install yarn (explanation for npm is true here as well)
  # for documentation, see https://yarnpkg.com/lang/en/docs/install-ci/#travis-tab
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.27.5
  - export PATH=$HOME/.yarn/bin:$PATH

before_script:
  # run yarn to install our dependencies from package.json
  - yarn

script:
  # pack libs, fonts, etc. together
  - node_modules/.bin/webpack -p
  - bundle exec gemoji extract sources/static/emoji
  # use additional config for CI (changes baseurl for GH Pages)
  # settings defined in later files overwrite ones from earlier files
  - bundle exec jekyll build --config _config.yml,_config_travis.yml 

deploy:
  # experimental feature to directly deploy static files to GH Pages
  provider: pages
  # prevent files from being removed
  skip_cleanup: true
  # set in travis-ci.org dashboard
  github_token: $GITHUB_TOKEN
  local_dir: site
  target_branch: gh-pages
  on:
    branch: development

env:
  global:
    # further speed up builds
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
