# Site settings
title: "ESE 2015 | iFSR"
email: ese@ifsr.de
emailfsr: fsr@ifsr.de
baseurl: "/2015" # the subpath of your site, e.g. /blog/
url: "https://ese.ifsr.de" # the base hostname & protocol for your site
twitter_username: ifsr
github_username:  fsr
color: "#573B75"

# Global Metatags
metatag:
  description: "Die offizielle Seite der ESE 2015. Hier findet Ihr alle wichtigen Informationen 端ber die Erst Semester Einf端hrung der Informatik an der TU Dresden."
  abstract:
  keywords:
  og:
    title: "ESE 2015 | iFSR"
    description: "Die offizielle Seite der ESE 2015. Hier findet Ihr alle wichtigen Informationen 端ber die Erst Semester Einf端hrung der Informatik an der TU Dresden."
    locale:
      locale:
      localealternate:
    image:
      image:
      secure_url:
      type:
    site_name:
    url:
    type:
  HandheldFriendly: true

# Completely useless since it seems like you can not access them
# In the way it would be neccessary for metatags
# defaults:
#   -
#     scope:
#       path: ""
#     values:
#   -
#     scope:
#       path: "en"
#     values:
#       metatag:
#         description: "The official site of ESE 2015. Here you can find all important information about the freshmen introduction of computer science at TU Dresden."
#         abstract: ""
#         keywords: ""
#         ogtitle: "ESE 2015 | iFSR"
#         ogdescription: "The official site of ESE 2015. Here you can find all important information about the freshmen introduction of computer science at TU Dresden."
#         oglocale:
#         oglocalealternate:
#         ogimage:
#         ogsecure_url:
#         ogtype:
#         ogsite_name:
#         ogurl:
#         ogtype:
#         HandheldFriendly: true

# Build settings
markdown: kramdown

exclude:
  - .c9
  - .git

permalink: none

compress_html:
  clippings: all
  comments: []
  endings: []
  profile: false
  ignore:
    envs: []

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "en"
      type: "en-posts"
    values:
      layout: "en-post"
  -
    scope:
      path: "en"
      type: "en"
    values:
      layout: "en-page"

sass:
  style: :compressed

collections:
  news:
  sidebar:
  en-news:
  en-sidebar:
  en:
    output: true
    permalink: en/:path:output_ext
